### ISSUE TITLE
Return of the Fluid and Source Bug

### ISSUE THREAD

**Issue by Drackion** [alec016/modular-machinery-reborn#12]
Mods:
 - MMR (Latest)
 - MMR Ars (Latest)
 - MMR Mek (Latest)
 - KJS (2101.7.1-build.181)
 
Issue:
Repeat of https://github.com/alec016/modular-machinery-reborn/issues/1 is happening on the latest version of MMR, causing fluid and source inputs to rapidly be consumed in recipes added via KJS.

**Comment by alec016** [comment]
try with this version of kj, 2101.7.1-build.190 is the version that i am using in the mod

**Comment by Drackion** [comment]
i can try with that version but 181 is the latest one i can use in the pack as it is the latest on CF

**Comment by Drackion** [comment]
tested with 190 still occurs

**Comment by alec016** [comment]
can you share one of the most vanilla machines and one of the recipes that it happens?

**Comment by Drackion** [comment]
the most vanilla one:
https://github.com/AllTheMods/ATM-10/blob/main/kubejs/server_scripts/mods/modular_machinery/multiblocks/atm/runic_crucible.js
https://github.com/AllTheMods/ATM-10/blob/main/kubejs/server_scripts/mods/modular_machinery/recipes/atm/runic_crucible.js
for the fluid to use the liquid aureal recipe
https://github.com/AllTheMods/ATM-10/blob/main/kubejs/startup_scripts/CustomAdditions.js#L33

**Comment by alec016** [comment]
Try with this [new version](https://we.tl/t-ZdQz8ckPIB)
If there is no issue i will upload the version adn update the mekanism, source and ae2 addons too

**Comment by Drackion** [comment]
the water isn't being consumed anymore when the recipe is incomplete

**Comment by alec016** [comment]
what is the issue with that?

**Comment by Drackion** [comment]
i am say the fluids are acting as intended now:
- old jar: fluids would be rapidly consumed with incomplete recipes
- new jar: with incomplete recipes fluids say in there not getting consumed until the missing ingredients are added

**Comment by alec016** [comment]
so, the issue is solved?

**Comment by Drackion** [comment]
yes
