### ISSUE TITLE
JEI Compatibility Issue

### ISSUE THREAD

**Issue by Aidenboss434** [alec016/modular-machinery-reborn#14]
When Using JEI With MMR The Recipes Show Broken
![image](https://github.com/user-attachments/assets/3784c753-65ea-4853-b621-e6a041b0a6fa)

**Comment by Derek1256** [comment]
you have to mark the UI things, which is the x, y is for in the examples.

**Comment by alec016** [comment]
does this question solved?

**Comment by Aidenboss434** [comment]
Thanks
