### ISSUE TITLE
Server Client Recipe Desync

### ISSUE THREAD

**Issue by Drackion** [alec016/modular-machinery-reborn#15]
Multiblocks and Recipes registered via kjs don't appear in client's JEI, players can temp fix it by joining a singleplayer world before a server.

**Comment by alec016** [comment]
will fix it soon

**Comment by alec016** [comment]
can you test if it is working now? https://we.tl/t-8aIZQzlJLU
in dev environment it works, but i know how it is, and sometimes the dev environment makes things that server doesnt do

**Comment by ghost** [comment]
The new jar does not seem to change any of the observed problematic behavior with items added by kubejs. If i try to /give myself the controller items the server crashes
https://mclo.gs/ZSaue1R
if i try to force a name onto the item when i do the /give via nbt the server times me out and there is no trace of any error to be found in any log.

**Comment by alec016** [comment]
@alekthefirst the jar is in both client and server? what is the command you used to get the controller?

**Comment by ghost** [comment]
> @alekthefirst the jar is in both client and server? what is the command you used to get the controller?

same jar in client and server
command with custom name is 
`/give alekthefirst modular_machinery_reborn:controller[modular_machinery_reborn:machine="atm:chemical_crystallizer",custom_name='"testname"'] `
which times me out, if i remove the custom name its just an instant server crash with the log provided earlier

this all works fine in single player

**Comment by alec016** [comment]
@alekthefirst 
the client has the same files loaded? i mean, the kubejs scripts, data/assets files, or just the things required by the client?

**Comment by ghost** [comment]
@alec016 yes they have the same files and kubejs scripts as provided in atm10 version 2.1

**Comment by alec016** [comment]
im dumb, i forgot to send the machines to the client.

**Comment by alec016** [comment]
https://we.tl/t-NyWVit8pfR there are 2 jars, the experiencelib jar is the new dependency to handle the next feature of the mmr

**Comment by ghost** [comment]
the new jars get me a disconnect on server join due to Non [a-z0-9_.-] character in a namespace, this also prevents me from joining single player worlds
https://mclo.gs/TcxQeko

**Comment by alec016** [comment]
i see the problem

**Comment by alec016** [comment]
https://we.tl/t-pqCneIqMkl try this

**Comment by alec016** [comment]
wait, it will crash again, i noticed something wrong again

**Comment by alec016** [comment]
https://we.tl/t-NLPRhZZmTg try it

**Comment by ghost** [comment]
still a disconnect due to Non [a-z0-9/._-] character, though the location is different.
https://mclo.gs/Qk0vKbz

**Comment by alec016** [comment]
https://we.tl/t-LnUPRcnep1 use this and set in the modular_machinery_reborn-common.toml
path: general.Logs -> debug_level="DEBUG"
and send me the mmr.log, i need to see what is happening with that thing

**Comment by alec016** [comment]
then you can set it again to INFO

**Comment by ghost** [comment]
this one behaved more like the first one, with successful server join the server crash when i /give a controller
MMR debug enabled on both client and server
[server.mmr.log](https://github.com/user-attachments/files/18070151/server.mmr.log) (https://mclo.gs/yABYD7i)
[client.mmr.log](https://github.com/user-attachments/files/18070155/client.mmr.log) (https://mclo.gs/IOdjydf)
[server-crash-log.txt](https://github.com/user-attachments/files/18070163/server-crash-log.txt) (https://mclo.gs/czHDzGG)

**Comment by alec016** [comment]
https://we.tl/t-Sr8hgPBKCx
i think now its fixed

**Comment by ghost** [comment]
hmm doesn't look like the server crash changed much
https://mclo.gs/O0Pt7O6
i also included a video this time so you can see how i test (sorry for quality but i need to keep the files small)
https://i.imgur.com/asgJxJq.mp4

**Comment by alec016** [comment]
i see the problem, it it trying to access a method that is marked that only exists on client.
https://we.tl/t-vvt16m4zLk with this, that error will be fixed

**Comment by ghost** [comment]
yes that does seem to be working now
thank you for your work

**Comment by alec016** [comment]
i will upload the update when i finish the experience feature (one or two days maybe)
