### ISSUE TITLE
Further issues on MMR 1.1.13

### ISSUE THREAD

**Issue by ghost** [alec016/modular-machinery-reborn#16]
Hi, we at the ATM team are testing the recent MMR + experience lib update to see if it fixes our server issues, but the update seems to break things differently than before.
I am now unable to connect to server at all without the client crashing.

Client crash report: https://mclo.gs/gpBuSZx
Client latest.log: https://mclo.gs/dgy7HoQ
Client MMR log with debug on: https://mclo.gs/FLfS6pV
Server latest.log (just a connection reset): https://mclo.gs/J5ujguK
Server MMR log with debug on: https://mclo.gs/zXy2itU
Video clip of event: https://i.imgur.com/ukUPgHg.mp4

**Comment by ghost** [comment]
Same issue now also extends to single player worlds, which i cannot join without crashing in the same manner
Crash log provided (Looks the same as the other one provided above): https://mclo.gs/BpkHwRq

**Comment by alec016** [comment]
can you try with this? https://we.tl/t-AI306W8oHZ

**Comment by ghost** [comment]
> can you try with this? https://we.tl/t-AI306W8oHZ

That seems to work better yeah, can join and can /give an item https://i.imgur.com/GV04ft4.mp4
The /give does come with a command error though, visible at the bottom of log here: https://mclo.gs/MvT4OlO

**Comment by alec016** [comment]
https://we.tl/t-1YO6I86T5x this should fix that command error

**Comment by ghost** [comment]
It does fix the command error, now the last issue i can find is: ~~If i am on a server, go back to the main menu then join a single player world, i am unable to sync registries from the server. Log of that: https://mclo.gs/atMZy7U
This does not happen if i go from single player world to single player world, nor if i go from single player to server.
There's nothing in the log that immediately points at MMR, so ill try to poke around some more.~~

**Comment by ghost** [comment]
can ignore the last issue, it happens even without MMR and experience lib
I am happy with 1.1.14 as it is in the last link you provided

**Comment by alec016** [comment]
good to know, i was trying to figure out what is the relation with mmr and couldnt find anything, there are so many errors from pneumatic registry

**Comment by alec016** [comment]
in a few minutes will be visible on curseforge
