### ISSUE TITLE
Further localizedName and tooltip issues on ATM10 with MMR 1.1.14

### ISSUE THREAD

**Issue by ghost** [alec016/modular-machinery-reborn#17]
Crashes reported by players of ATM10.
I will work on replicating these in my local instance when i find time, just dropping the logs and user descriptions here in the mean time (descriptions paraphrased by me)

User on a dedicated server described these two as "When hovering over items in JEI and viewing recipes"
localizedName crash: https://mclo.gs/efv0NbZ
ingredient tool tip crash: https://mclo.gs/NWQMue0

User, client-server relation unknown, described this as "for doing runic enchanter template in building gadgets template manager"
They were using the template manager to get the full block list, because the one in the controller GUI did not manage to include all the different blocks required. They also noted that some of the other multi blocks worked, before crashing on this one. Removing the controller specifically did not resolve the issue.
https://mclo.gs/4v54tii

User on a dedicated server described this as "Opening ars noveau storage lectern, there are no MMR blocks in said storage" This crash has been repeated by several other users of the ars noveau storage solution too.
https://mclo.gs/yNKqlzj

**Comment by alec016** [comment]
if you can manage to reproduce the issue, i think with this version is solved, but to be sure, i would like if you can test it before i upload it to cf. https://we.tl/t-r1xLTpqLHT

**Comment by ghost** [comment]
> if you can manage to reproduce the issue, i think with this version is solved, but to be sure, i would like if you can test it before i upload it to cf. https://we.tl/t-r1xLTpqLHT

i can't load this due to not having access to experience lib 1.0.2

**Comment by alec016** [comment]
my bad, i forgot about that, i upload it https://we.tl/t-Mv8eiT01gB

**Comment by ghost** [comment]
i was able to replicate the ars noveau storage lectern crash on the old version of MMR, and can verify that this new one fixes that
i am still working on the other two.

**Comment by ghost** [comment]
alright i have been able to replicate the building gadgets template crash and can confirm that 1.1.15 fixes that

**Comment by ghost** [comment]
I cannot replicate the JEI crashes, other than making the GUI of one of the bigger recipes look bugged, which is probably more our fault anyway.
I do like the update though as it is. One of the JEI crashes i linked is very likely to be fixed by 1.1.15 as it shares a very similar stack trace, the other one i am less sure of but the future will tell if it remains a problem

**Comment by alec016** [comment]
perfect, i will update it to cf right after the confirmation of the issue of the config not updating the values with the version i passed you

**Comment by ghost** [comment]
It seems that changing config values for hatches still do not change in game values on MMR 1.1.15

**Comment by ghost** [comment]
i see now that the config thing was an atm team issue, sorry for the inconvenience
