### ISSUE TITLE
Multi Blocks failing to detect hatches

### ISSUE THREAD

**Issue by Drackion** [alec016/modular-machinery-reborn#18]
got reports from users that the custom multi blocks are failing to detect hatches when given recipe items despite the hatches being there

![image](https://github.com/user-attachments/assets/0b52b608-eee5-4bc2-b22a-8158d8a38bb5)
![2024-12-14_19 11 25](https://github.com/user-attachments/assets/78e053ef-df21-4b05-b5dc-5ded102fb79b)

**Comment by alec016** [comment]
i cant verify anything just with those images, i need abit more info about the problem if possible

**Comment by Drackion** [comment]
in the case of the Runic Crucible after building it and adding the hatches it forms with no issue, but when you add ingredients to craft a recipe the controller will flash between `No recipe found` and `No Fluid Output found` even tho there is a fluid output hatch

**Comment by alec016** [comment]
it only happens with the fluid hatch? or it happens with other ones?

**Comment by Drackion** [comment]
it happens with others i have seen it happen with item hatches too

**Comment by alec016** [comment]
and energy too, i fixed it already, recomended break and place the hatch/bus to update the buffers
https://we.tl/t-UoiWviubGB if you want to test it before upload it

**Comment by Drackion** [comment]
i'll test it rn

**Comment by Drackion** [comment]
tested recipes with items, fluids and energy and confirmed it fixes it
