### ISSUE TITLE
Game crashes when I place the machine controller

### ISSUE THREAD

**Issue by pynickle** [alec016/modular-machinery-reborn#19]
As the title says, l use the latest version 1.1.17, my log is as follows

https://gist.github.com/87f478556bee47266e7550ad87c55a44.git

**Comment by pynickle** [comment]
[crash-2024-12-17_21.30.29-server.txt](https://github.com/user-attachments/files/18166248/crash-2024-12-17_21.30.29-server.txt)

Also crash report here

**Comment by alec016** [comment]
As i said on discord, i already fin that issue but i didnt upload it. I will upload it as soon as i finish the breaking structure feature.

**Comment by pynickle** [comment]
> As i said on discord, i already fin that issue but i didnt upload it. I will upload it as soon as i finish the breaking structure feature.

Thank you for your reply and sorry for the intrusion
