### ISSUE TITLE
Blueprint not functional to display the multiblock

### ISSUE THREAD

**Issue by ghost** [alec016/modular-machinery-reborn#21]
Relaying https://github.com/AllTheMods/ATM-10/issues/1467
User clicks blueprint item on controller, nothing happens.
I will work on reproducing this myself when i find time.

**Comment by alec016** [comment]
well that should be fixed in the latest update already published, in any case im working on a GUI redo(almost done)

**Comment by ghost** [comment]
Ah i didn't see any mention of it in the 1.1.17 changelog

**Comment by ghost** [comment]
I have asked the user to manually update MMR, hopefully they respond positively

**Comment by alec016** [comment]
its not a problem with the blueprint, was a problem trying to use some client marked stuff on the server

**Comment by ghost** [comment]
I see, ill mark this as completed then
