### ISSUE TITLE
Further issues wth hatches

### ISSUE THREAD

**Issue by ghost** [alec016/modular-machinery-reborn#22]
Relaying https://github.com/AllTheMods/ATM-10/issues/1463
From reading complaints from our users on our discord, it seems the multiblocks loses tracking of hatches, fluid hatches specifically, when the user is changing dimensions or otherwise reloading the level, meaning a multiblock that was functional will revert to a "missing structure" status.
I will work on reproducing this when i find time.

**Comment by alec016** [comment]
i will rey to figure out what is going on with that, i noticed it with energy hatch

**Comment by alec016** [comment]
in which ones happens? can you ask the user for which ones it happens to him?

**Comment by ghost** [comment]
Am reproducing now
here is the functional structure
![image](https://github.com/user-attachments/assets/913bea29-df4f-4d0f-b435-1882519ead51)
if i then leave and rejoin the world it starts flipping between no matching recipe and no energy input hatch found
![image](https://github.com/user-attachments/assets/e6298e11-d61c-48c1-82c0-5d0f10e298e5)

It also troubled me with missing fluid hatches that didn't get fixed until i replaced both the fluid and item hatches, but am presently not able to get that to happen again

**Comment by ghost** [comment]
Testing once again, but this time without any fluids in the fluid hatches
![image](https://github.com/user-attachments/assets/376a3567-669d-4bc4-bf7d-79073f8dd3da)
on joining the world its fine
![image](https://github.com/user-attachments/assets/35d12e57-d5f5-459f-b7a9-a800b88ba002)
But if i then add fluids, it starts complaining about energy input hatch

https://github.com/user-attachments/assets/eac638cf-e374-498a-9de9-98ce816576b9

**Comment by ghost** [comment]
Issue also seems to affect auto placed structures, i find i need to break and replace the hatches myself to get them recognized.

**Comment by ghost** [comment]
and when doing that on the 1.1.18 jar you sent, i now get a new issue when its time to actually process recipes

https://github.com/user-attachments/assets/fe1111de-0b67-4e28-9287-73b42a154130

**Comment by alec016** [comment]
the recipe stuff was a mistake, i put something additional and break it

**Comment by alec016** [comment]
this version should fix the hatches issues and the recipe mistake https://we.tl/t-PCzqMxl0SZ

**Comment by ghost** [comment]
The update seems to have worked, i have tested world unload/reloading, server restarts and dimension hopping to unload chunks both in single and multi player, and it no longer reverts to missing hatches (testing with 4 random multiblocks from our selection). And it continues processing the recipe for the items/fluids i had put into the hatches.
The blueprint is working, both in single and multi player.
Placing controllers do not crash the game, also tested in single and multi player.

Last thing i am noticing is: if the structure has unused energy input hatches, it will complain about missing energy even if the one that is used has enough energy to do the craft.
Video of what i mean:

https://github.com/user-attachments/assets/88050754-cb6e-4f4a-96a3-cb2c127750b0

I also tested this with having an unused item input hatch, and it does not suffer the same issue

**Comment by ghost** [comment]
And if i have a fluid hatch that's missing a fluid that's needed for all valid recipes, then it will complain about missing fluid hatch, even though it might be more fitting no have a no matching recipe warning
Example of what i mean: if i empty the hatch with the green xp fluid (not needed for all the recipes) then its fine
but if i take out the light blue aureal (needed for all recipes) then it reverts to missing fluid hatch

https://github.com/user-attachments/assets/4e9e3243-2360-4b6c-a6ad-0aa450e7f49d

Adding the aureal fluid back into the hatch resolves the missing hatch issue

https://github.com/user-attachments/assets/80aa02c6-59db-4d94-85c9-784fb553940c

Would be nice to clear up this confusion, its ok for people that "know" the multiblock will complain until the fluids are added, but most people will not know this

EDIT for clarity: this warning only shows up if *some* of the hatches have fluids, but not enough to fulfill any recipes

**Comment by alec016** [comment]
> https://github.com/alec016/modular-machinery-reborn/issues/22#issuecomment-2557083548

i know what is causing it, i can fix it easy

> https://github.com/alec016/modular-machinery-reborn/issues/22#issuecomment-2557117383

thats the crafting message system, it shows an error message if at least the 50% of requirements are present and are valid. i think i can be more specific with the messages of the error if it is a problem for the users to use it

**Comment by ghost** [comment]
Ah, new recipe issue
in single player these all correctly make different controllers, but in multiplayer they all make the same controller

https://github.com/user-attachments/assets/836423a6-cf50-4ac1-9710-b42213e4b113

Can confirm that after crafting it makes the wrong controller

**Comment by alec016** [comment]
it shows any error in server logs?

**Comment by ghost** [comment]
No errors in either mmr.log nor latest.log
server mmr.log (debug enabled): https://mclo.gs/mCU4kKl
server latest.log(no errors to note): https://mclo.gs/5xACuFO 
though i will note in mmr.log it seems the recipe outputs (for example the chemical washer recipe) are set wrong, to automatic hephaestus forge.to see this go to far end of line 560 of mmr.log
this is also present in client mmr.log so i dont know if its related, in client these recipes work fine, they only break in mp

**Comment by alec016** [comment]
i was looking into the atm10 logs(i had the same issue in singleplayer) and see this
![image](https://github.com/user-attachments/assets/40ac004f-9979-4ebe-800c-70e171eb605e)

it can be a problem when serializing the recipe from kubejs an error on the recipe script or an error when trying to retrieve the recipe from the server

**Comment by alec016** [comment]
i saw the problem, it also happens with runic enchanter enchanted books

**Comment by ghost** [comment]
Hmm i'm not good enough with kubejs to make any worthwhile changes there, ill see if i can get Drack on it

**Comment by ghost** [comment]
As of right now it seems the recipe issue is caused by us, either by us doing something wrong in kubejs or by optimization code in alltheleaks.
