### ISSUE TITLE
Crash on controller placement on 1.1.17

### ISSUE THREAD

**Issue by ghost** [alec016/modular-machinery-reborn#23]
Crashing on placing a controller on MMR 1.1.17, was not an issue on 1.1.16
After this, joining the world becomes impossible from the same crash
log of crash: https://mclo.gs/yvVn45g
video of crash: 

https://github.com/user-attachments/assets/4d08c072-6260-48f9-97a7-50e1a167842a

**Comment by alec016** [comment]
ah, i forgot about that in that version sorry, i already fix it for the next update
https://we.tl/t-KewxkFyeaF this file fixes #23 #21

**Comment by ghost** [comment]
Have downloaded and can confirm that placing controllers no longer crash me
