### ISSUE TITLE
low performance on ATM 10 , any idea?

### ISSUE THREAD

**Issue by shinobi9** [alec016/modular-machinery-reborn#25]
modular-machinery-reborn version 1.1.15
ATM 10 2.4
![image](https://github.com/user-attachments/assets/62ac4897-2399-4dc2-b8cc-53d88828d98d)

**Comment by alec016** [comment]
since that version were many updates fixing many things and making optimizations, try to update and see how it goes

**Comment by shinobi9** [comment]
https://observable.tas.sh/p/hhne

![image](https://github.com/user-attachments/assets/ab96af4e-9f69-45c4-bb30-5230d8d9b1a3)

upgraded mod，still 7000+

**Comment by alec016** [comment]
can be direct proportional to the size of the multiblock, testing ones are around 120, still high, i will try to improve that numbers

**Comment by shinobi9** [comment]
ATM use 500+ blocks...

**Comment by alec016** [comment]
i tried it myself and see in my pc around 100, so, it can be caused by low performance on your pc or lag in your world, i cant do that much to improve the performance, i already did everything i could to do the less checks possible per tick

**Comment by shinobi9** [comment]
https://observable.tas.sh/p/hhne/aggregated
576 hydroponic_bed cost less time 
is there any way to check every 20 tick instead of per tick or just check before craft ?

**Comment by alec016** [comment]
the recipes has a time checker in the config, same with the structure, the structure shold be the highest cost, if i remember correctly by default it checks the structure once per second, took into the config and change the values if needed

**Comment by shinobi9** [comment]
found in modular_machinery_reborn-common.toml
[general.General]
check_structure_ticks  = 5
check_recipe_ticks =  20
both default value , config solved my problem
