### ISSUE TITLE
JEI Recipe Screen Suggestion

### ISSUE THREAD

**Issue by Drackion** [alec016/modular-machinery-reborn#4]
I'd like to suggest some changes to have more control over the JEI recipe screen as right now the space provided quite limiting.
Suggested changes:
- Shrink Fluid, Chemical & Source Displays to be the same as items
- Change Power displays to be like duration and be text at the bottom of the screen
- Ability to move the progress bar
- Ability to have a wider display area

With how things are the screen easily gets cluttered with fluids, source, chemicals and energy due to their massive size and the fact the progress bar is static doesn't help either.

![image](https://github.com/user-attachments/assets/8e221e77-604d-46e9-94b5-206677a0890a)

**Comment by alec016** [comment]
i will change it, i used the original textures for most of the things. unfortunetly im not good in making textures, so, making it as if they are similar to items can be easy to do

**Comment by alec016** [comment]
i think it has the maximum size that jei can use(width)
and the progress bar should be easy to implement the ability to move it

**Comment by alec016** [comment]
i upload an update with the changes maded, thw unique one i dont want to change that much is the energy, i prefer staying as a bar, i made it with less height to match exacty 3 item slots in column, the fluid chemical and source now has the same size as item slot, and texts renders brom bottom to top(currently is just the duration of the recipe), you can change the size of each recipe individually and move the progress for each recipe too

**Comment by Drackion** [comment]
thx
