### ISSUE TITLE
Generate products with a certain probability

### ISSUE THREAD

**Issue by lostmyself8** [alec016/modular-machinery-reborn#7]
Can you add the functions of probability generation of products and non consumption of reactants,I think this will make the recipe more diverse. : )

**Comment by alec016** [comment]
some of the requirements has it in json, i forgot to add it in kubejs tho, thanks for remember me that, i will fix it in the next update

**Comment by lostmyself8** [comment]
thanks

**Comment by lostmyself8** [comment]
excuse me，How should I use them

**Comment by alec016** [comment]
with kubejs is not possible using chance right now, but with json, it just need to add the property "chance" and needs to be between 0 and 1.
Are only supported: fluid, item, chemical and source

**Comment by alec016** [comment]
in the next updates(im not sure i which one) i will add it to kubejs too

**Comment by lostmyself8** [comment]
ok,thanks
