### ISSUE TITLE
Configs revert on startup

### ISSUE THREAD

**Issue by Satherov** [alec016/modular-machinery-reborn#8]
When starting your game, the configs get reverted back to their original state

**Steps to reproduce**
- Open any configs
- Edit any of the values
- Start your game

-> If you have the editor open next to your game you can watch the values revert during startup

**Comment by alec016** [comment]
should be fixed with the last update, i remove the cloth config dependency entirely

**Comment by Satherov** [comment]
Works as intended, thanks
